spring:
  application:
    name: backend
  profiles:
    include: dev

  # ===============================
  # H2 Database Configuration -- TEMP DB
  # ===============================
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:

  # ===============================
  # JPA / Hibernate
  # ===============================
  # ? JPA? Flyway?? ?? ??????
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

  # ===============================
  # mysql Database Configuration
  # ===============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: factor2al

  # ===============================
  # Flyway Connection
  # ===============================
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    baseline-on-migrate: false

  # ===============================
  # H2 Console
  # ===============================
  h2:
    console:
      enabled: true
      path: /h2-console

  # ===============================
  # kafka
  # ===============================
  kafka:
    bootstrap-servers: 43.200.39.139:9092
    consumer:
      group-id: monitory-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  # ===============================
  # Server Port
  # ===============================
  port: 8080

logging:
  # ===============================
  # Debug mode
  # ===============================
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  # Swagger URL
  swagger-ui:
    path: /docs

# [NOTICE] AWS IAM credentials are loaded from external environment variables.
# Be sure to set the values in a .env file or as environment variables in the operating environment.
# Never write the actual key values directly in this file (security risk and risk of Git exposure).
aws:
  access-key: ${AWS_IAM_ACCESS_KEY}
  secret-key: ${AWS_IAM_SECRET_KEY}
  region: ap-northeast-2 